### PR TITLE
Padding

### PR DESCRIPTION
**Pull request by pantaray**
Author Guidelines
-----------------
- [X] Is the change set **< 400 lines**?
- [X] Was the code checked for memory leaks/performance bottlenecks?
- [X] Is the code running locally **and** on the ESI cluster?
- [X] Is the code running on all supported platforms?

Reviewer Checklist
------------------
- [ ] Are testing routines present?
- [ ] Do **parallel** loops have a set length and correct termination conditions?
- [ ] Do objects in the global package namespace perform proper parsing of their input? 
- [ ] Do code-blocks provide novel functionality, i.e., no re-factoring using builtin/external packages possible?
- [ ] Code layout
  - [ ] Is the code PEP8 compliant?
  - [ ] Does the code adhere to agreed-upon naming conventions?
  - [ ] Are keywords clearly named and easy to understand?
  - [ ] No commented-out code?
- [ ] Are all docstrings complete and accurate?

### CODE REVIEW

**Review by tensionhead — COMMENTED** [review]
So regarding the meta-functions accepting numpy arrays, what is the expected shape encoding?

**Review by tensionhead — CHANGES_REQUESTED** [review]
So I naively did a `from syncopy.datatype import padding` and tried to pad the test data generated by `tdat = generate_artificial_data(inmemory=True, seed=1230, nTrials=5)` but failed. Reason is that there is no default `padtype` and the doc just says
`padtype : str` so as a newbie user I got no idea what to do now. I strongly suggest setting a default `padtype` (which 99% of users want) and extending the doc respectively!

**Comment by pantaray** [comment]
> So I naively did a `from syncopy.datatype import padding` and tried to pad the test data generated by `tdat = generate_artificial_data(inmemory=True, seed=1230, nTrials=5)` but failed. Reason is that there is no default `padtype` and the doc just says `padtype : str` so as a newbie user I got no idea what to do now. I strongly suggest setting a default `padtype` (which 99% of users want) and extending the doc respectively!

We can introduce a default `padtype`, however, the doc is pretty clear here, that `padtype` is a mandatory argument without default as in the [FieldTrip template](https://www.fieldtriptoolbox.org/reference/ft_preproc_padding/ )

**Comment by pantaray** [comment]
> So regarding the meta-functions accepting numpy arrays, what is the expected shape encoding?

So far, no expectations, really, since the decorator does not really know what the meta-function is up to. The offending decorator just assumed that every Syncopy meta function must accept (at least) one Syncopy object. If the positional args of the meta function did not contain any Syncopy object, an exception was raised. Now `padding` is the first example of a meta-function where this limitation seems too restrictive (and I guess more meta-functions like it might turn up in the future).

**Pull request merged**
