### PR TITLE
434 add plotting for spikedata

### PR DESCRIPTION
**Pull request by tensionhead**
Changes Summary
----------------
- `singlepanelplot` and `multipanelplot` for `SpikeData`
- can plot either indexed by unit or channel
- hotfix `_trial_ids` für DiscreteData
- form is a so called "spike raster plot":
Screenshot from 2023-05-30 17:41:25

Reviewer Checklist
------------------
- [x] Are testing routines present?
- [x] Do objects in the global package namespace perform proper parsing of their input? 
- [x] Are all docstrings complete and accurate?
- [x] Is the CHANGELOG.md up to date?

### CODE REVIEW

**Review by dfsp-spirit — APPROVED** [review]
very nice plots, and good to have them plot unit instead of channel. I guess people like Katharine are more qualified than me to comment on them, but from what I see online, this is suitable. some people seem to plot a single neuron, with the trials on the y axis, but if really needed, we can add that later.

**Comment by tensionhead** [comment]
Thx for the review! I'll ping @kshapcott and @Cumol directly, adding the trial axis is not a biggy I think.

**Comment by dfsp-spirit** [comment]
Since there have been no replies yet, I would now merge this so it can be used, e.g., for the docs. If we need some minor changes (e.g., add labels to multi-channel plots) or additions (like trial axis), we can add them later.

**Comment by Cumol** [comment]
sorry for the lack of response. looks good! will give it a try in the next week or two when I am touching spike data again.

Another typical plot is to plot one unit over multiple trials. So the x-axis would be time, y axis would be trials, and the subplots would be for each unit.

What do yu say @KatharineShapcott ?

**Comment by KatharineShapcott** [comment]
Yes I agree, x-axis time, y axis trials.

**Pull request merged**
