### PR TITLE
Spike waveform

### PR DESCRIPTION
**Pull request by KatharineShapcott**
Changes Summary
----------------
- New waveform property for SpikeData objects

Reviewer Checklist
------------------
- [ ] Are testing routines present?
- [ ] Do objects in the global package namespace perform proper parsing of their input? 
- [ ] Are all docstrings complete and accurate?
- [ ] Is the CHANGELOG.md up to date?

### CODE REVIEW

**Comment by KatharineShapcott** [comment]
@dfsp-spirit Can you take a look at this and see what I'm doing wrong? Maybe adding in the chunking was a mistake?

**Comment by dfsp-spirit** [comment]
Yes, I will have a look!

**Comment by dfsp-spirit** [comment]
@KatharineShapcott  I think I have an idea what is going on, I will try to fix it.

**Comment by dfsp-spirit** [comment]
@KatharineShapcott Something is really off with this branch, I noticed it did not have the latest dev also. I have transferred your changes to this new PR and branch `waveform`: [PR 437](https://github.com/esi-neuroscience/syncopy/pull/437) that is now green.

I also added some tests for the current functionality.

What you should think about is the behavior you want for selections, e.g., what should happen to the waveform if a selection is applied to the data (I guess you want to only select the respective part of the waveform then). You should add a test and selection logic for that, if such a thing is needed. If not, I guess this is pretty much it.

**Comment by dfsp-spirit** [comment]
Closing in favor of PR 437.

**Pull request closed without merging**
