### PR TITLE
Fix: tags loaded precisely

### PR DESCRIPTION
**Pull request by KatharineShapcott**
Previously part matches of tags were also loaded

Author Guidelines
-----------------
- [x] Is the change set **< 600 lines**?
- [ ] Was the code checked for memory leaks/performance bottlenecks?
- [ ] Is the code running locally **and** on the ESI cluster?
- [ ] Is the code running on all supported platforms?

Reviewer Checklist
------------------
- [ ] Are testing routines present?
- [ ] Do **parallel** loops have a set length and correct termination conditions?
- [ ] Do objects in the global package namespace perform proper parsing of their input? 
- [ ] Do code-blocks provide novel functionality, i.e., no re-factoring using builtin/external packages possible?
- [ ] Code layout
  - [ ] Is the code PEP8 compliant?
  - [ ] Does the code adhere to agreed-upon naming conventions?
  - [ ] Are keywords clearly named and easy to understand?
  - [ ] No commented-out code?
- [ ] Are all docstrings complete and accurate?
- [ ] Is the CHANGELOG.md up to date?

### CODE REVIEW

**Comment by KatharineShapcott** [comment]
If you want the previous behaviour then you can add a star into the tag name itself e.g. `tag='lfp*'`

**Comment by tensionhead** [comment]
@KatharineShapcott thx for your contributions! Could you please reopen this PR to merge into `dev` not `master`? Thx 🙂

**Comment by tensionhead** [comment]
One more comment: please branch out from `dev`, not from `master` when you want to commit your changes. We should probably make this rule more visible to contributors. I think in this case it is fine, so just go ahead 🚀

**Comment by KatharineShapcott** [comment]
Sorry I usually do, mistake thanks for fixing it! Still trying to figure out why this test is failing atm.

**Comment by tensionhead** [comment]
Hey @KatharineShapcott you want to pick up in this again? Otherwise I could also have a look into the `SpyIO Error`, as I right now don't see how this could be connected to the changes you made?!

**Comment by KatharineShapcott** [comment]
I suspect it is a real error because I removed the trailing '*', assuming that files will always end with the tag and then immediately their extension. It seems in this test that's not the case but I can't get it to run properly on my machine so I can't check the file names. Don't have time to work on this at the moment. :/

**Comment by tensionhead** [comment]
Ok I see, from our side this is not top-priority, as opposed to many other open issues.. If you find time again some time in the future would be great of course :slightly_smiling_face:

**Comment by dfsp-spirit** [comment]
I am closing this for now, feel free to re-open when we continue working on it.

**Pull request closed without merging**
